definitions:
  shared.Credentials:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  title: All ways to auth
  version: "1.0"
paths:
  /basic-secure:
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BasicAuth: []
      summary: Secured endpoint
      tags:
      - basic
  /session/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/shared.Credentials'
      produces:
      - application/json
      responses: {}
      tags:
      - session
  /session/logout:
    post:
      produces:
      - application/json
      responses: {}
      tags:
      - session
  /session/refresh:
    post:
      produces:
      - application/json
      responses: {}
      tags:
      - session
  /session/secure:
    get:
      produces:
      - application/json
      responses: {}
      tags:
      - session
  /token/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/shared.Credentials'
      produces:
      - application/json
      responses: {}
      tags:
      - token
  /token/secure:
    get:
      produces:
      - application/json
      responses: {}
      tags:
      - token
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
